name: auto-tagging

on:
    # 每当 push 到 main 分支时触发部署
    # Deployment is triggered whenever a push is made to the main branch.
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    tagging:
        runs-on: ubuntu-latest
        steps:
            - name: Creating Tag
              uses: anothrNick/github-tag-action@v1.38.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag-prefix: "v"
                  release-branch: main
                  default-branch: main
                  create-annotated-tag: true
                  tag-message: "chore(release): $TAG"
                  commit-message: "chore(release): $TAG"
                  push-branch: main
