# example 1: on push to master
name: Bump version & Tagging
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Create Tagss
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        tag_prefix: 'v' # optional, default is ''
        release_branches: 'main' # optional, default is 'main'
        initial_version: '1.0.1' # optional, default is '0.1.0'